# Generated by Django 4.1.3 on 2022-12-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_date_added_lead_description_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email2',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
