# Generated by Django 4.1.3 on 2022-12-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email2',
        ),
    ]
